zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20220829/ioncube_loader_lin_8.2.so
memory_limit=128M
upload_max_filesize=12M
post_max_size=12M
max_execution_time=30
display_errors=On
date.timezone=Europe/London
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
session.save_path="/tmp"
magic_quotes_gpc=Off